version: '3.8'

services:
  oracle-api:
    build: .
    container_name: oracle-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
      - ./root:/app/root
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - oracle-net

networks:
  oracle-net:
    driver: bridge